name: Test and release
on:
    push:

jobs:
    test-and-build:
        runs-on: ubuntu-20.04
        steps:
            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.18

            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Build
              run: "make build"

            - name: Test
              run: "make coverage"

            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              if: github.ref == 'refs/heads/main'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

            - uses: actions/upload-artifact@v3
              with:
                  name: binary
                  path: .build/

    release-binary:
        runs-on: ubuntu-20.04
        needs: ["test-and-build"]
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: binary
                  path: .build/

            - name: Release binaries to GitHub releases
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      .build/webhook-conversion-service

    release-docker:
        runs-on: ubuntu-20.04
        needs: ["test-and-build"]
        if: contains(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - uses: actions/download-artifact@v3
              with:
                  name: binary
                  path: .build/

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Create docker tags
              id: meta
              uses: docker/metadata-action@v3
              with:
                  images: ghcr.io/keskad/webhook-conversion-service

            - name: Build and relase docker
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
